# Generated by Authkit.
#
# Add fields to the users table for managing authentication.
#
class AddAuthkitFieldsToUsers < ActiveRecord::Migration
  def self.up
    add_column :users, :email, :string, :default => "", :null => false
    add_column :users, :password_digest, :string, :default => "", :null => false
    add_column :users, :time_zone, :string, :default => "Eastern Time (US & Canada)"
    add_column :users, :first_name, :string
    add_column :users, :last_name, :string
    add_column :users, :bio, :text
    add_column :users, :website, :string
    add_column :users, :phone_number, :string
    add_column :users, :username, :string, :limit => 64

    # Forgot password / Password reset
    add_column :users, :reset_password_token, :string
    add_column :users, :reset_password_sent_at, :datetime

    # Remember
    add_column :users, :remember_token, :string
    add_column :users, :remember_created_at, :datetime
    add_column :users, :remember_expires_at, :datetime

    # Confirmation
    add_column :users, :unconfirmed_email, :string
    add_column :users, :confirmation_token, :string
    add_column :users, :confirmed_at, :datetime

    # Tracking
    add_column :users, :sign_in_count, :integer, :default => 0
    add_column :users, :current_sign_in_at, :datetime
    add_column :users, :last_sign_in_at, :datetime
    add_column :users, :current_sign_in_ip, :string
    add_column :users, :last_sign_in_ip, :string

    # Analytics
    add_column :users, :original_source, :string
    add_column :users, :session_source, :string
    add_column :users, :first_visit_at, :datetime
    add_column :users, :last_visit_at, :datetime

    # Lockout
    add_column :users, :failed_attempts, :integer, :default => 0
    add_column :users, :locked_at, :datetime
    add_column :users, :unlock_at, :datetime
    add_column :users, :unlock_token, :string

    add_index :users, :email
  end

  def self.down
    drop_column :users, :email
    drop_column :users, :password_digest
    drop_column :users, :time_zone
    drop_column :users, :first_name
    drop_column :users, :last_name
    drop_column :users, :bio
    drop_column :users, :website
    drop_column :users, :phone_number
    drop_column :users, :username

    # Forgot password / Password reset
    drop_column :users, :reset_password_token
    drop_column :users, :reset_password_sent_at

    # Remember
    drop_column :users, :remember_token
    drop_column :users, :remember_created_at
    drop_column :users, :remember_expires_at

    # Confirmation
    drop_column :users, :unconfirmed_email
    drop_column :users, :confirmation_token
    drop_column :users, :confirmed_at

    # Tracking
    drop_column :users, :sign_in_count
    drop_column :users, :current_sign_in_at
    drop_column :users, :last_sign_in_at
    drop_column :users, :current_sign_in_ip
    drop_column :users, :last_sign_in_ip

    # Analytics
    drop_column :users, :original_source
    drop_column :users, :session_source
    drop_column :users, :first_visit_at
    drop_column :users, :last_visit_at

    # Lockout
    add_column :users, :failed_attempts
    add_column :users, :locked_at
    add_column :users, :unlock_at
    add_column :users, :unlock_token
  end
end

