# Generated by Authkit.
#
# Create a users table for managing authentication. Fields to handle
# the authentication are created in the AddAuthkitFieldsToUsers
# migration.
#
class CreateUsers < ActiveRecord::Migration
  def self.up
    create_table :users do |t|
      t.timestamps
    end
  end

  def self.down
    drop_table :users
  end
end
